FROM --platform=${BUILDPLATFORM:-linux/amd64} alpine:edge

# install git, cron
RUN apk update && \
    apk upgrade && \
    apk add --no-cache git cronie


# /blocklists is a volume that will host the blocklists

WORKDIR /blocklists

RUN git clone --depth 1 https://github.com/StevenBlack/hosts /blocklists

# add the update script
RUN echo "#!/bin/sh" >> /etc/periodic/15min/updateblocks.sh
RUN echo "cd /blocklists && git reset --hard HEAD && git pull --depth 1 origin master" >>  /etc/periodic/15min/updateblocks.sh

RUN chmod +x /etc/periodic/15min/updateblocks.sh

# start cron
CMD ["crond", "-f", "-s"]


